---
# Deployment for TechChallenge db backend
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: servian-backend-deployment
spec:
  serviceName: "servian-backend"
  replicas: 1
  selector:
    matchLabels:
      app: servian-backend
  template:
    metadata:
      labels:
        app: servian-backend
    spec:
      containers:
        # PostgreSQL DB container
        - name: db
          image: postgres:10
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: db-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pv-data

---
# Exposes database internally
apiVersion: v1
kind: Service
metadata:
  name: servian-backend-service
spec:
  type: ClusterIP
  selector:
    app: servian-backend
  ports:
    - port: 5432
      targetPort: 5432

---
# Creates persistent storage for the database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
